// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfig(arg1) {
  return window['go']['main']['App']['AddConfig'](arg1);
}

export function AddExcludedApp(arg1, arg2) {
  return window['go']['main']['App']['AddExcludedApp'](arg1, arg2);
}

export function AddResource(arg1, arg2) {
  return window['go']['main']['App']['AddResource'](arg1, arg2);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function ClearConfigCountry(arg1) {
  return window['go']['main']['App']['ClearConfigCountry'](arg1);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteExcludedApp(arg1) {
  return window['go']['main']['App']['DeleteExcludedApp'](arg1);
}

export function DeleteResource(arg1) {
  return window['go']['main']['App']['DeleteResource'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppearance() {
  return window['go']['main']['App']['GetAppearance']();
}

export function GetBetaUpdates() {
  return window['go']['main']['App']['GetBetaUpdates']();
}

export function GetGlassEffect() {
  return window['go']['main']['App']['GetGlassEffect']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetRoutingState() {
  return window['go']['main']['App']['GetRoutingState']();
}

export function GetShowProxySettings() {
  return window['go']['main']['App']['GetShowProxySettings']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ListExcludedApps() {
  return window['go']['main']['App']['ListExcludedApps']();
}

export function ListResources() {
  return window['go']['main']['App']['ListResources']();
}

export function LookupCountry(arg1) {
  return window['go']['main']['App']['LookupCountry'](arg1);
}

export function PickExcludedAppExe() {
  return window['go']['main']['App']['PickExcludedAppExe']();
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function PopularResources() {
  return window['go']['main']['App']['PopularResources']();
}

export function ReadLog() {
  return window['go']['main']['App']['ReadLog']();
}

export function ReconnectActive() {
  return window['go']['main']['App']['ReconnectActive']();
}

export function RoutingHealth() {
  return window['go']['main']['App']['RoutingHealth']();
}

export function SetAppearance(arg1, arg2) {
  return window['go']['main']['App']['SetAppearance'](arg1, arg2);
}

export function SetAppsEnabled(arg1) {
  return window['go']['main']['App']['SetAppsEnabled'](arg1);
}

export function SetAppsInclude(arg1) {
  return window['go']['main']['App']['SetAppsInclude'](arg1);
}

export function SetAutoConfigs(arg1) {
  return window['go']['main']['App']['SetAutoConfigs'](arg1);
}

export function SetAutoEnabled(arg1) {
  return window['go']['main']['App']['SetAutoEnabled'](arg1);
}

export function SetBetaUpdates(arg1) {
  return window['go']['main']['App']['SetBetaUpdates'](arg1);
}

export function SetConfigGeo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetConfigGeo'](arg1, arg2, arg3, arg4);
}

export function SetGlassEffect(arg1) {
  return window['go']['main']['App']['SetGlassEffect'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetRoutingMode(arg1) {
  return window['go']['main']['App']['SetRoutingMode'](arg1);
}

export function SetShowProxySettings(arg1) {
  return window['go']['main']['App']['SetShowProxySettings'](arg1);
}

export function SetSmartConfigs(arg1) {
  return window['go']['main']['App']['SetSmartConfigs'](arg1);
}

export function SetSmartEnabled(arg1) {
  return window['go']['main']['App']['SetSmartEnabled'](arg1);
}

export function SetSmartSites(arg1) {
  return window['go']['main']['App']['SetSmartSites'](arg1);
}

export function StartProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopProxy(arg1) {
  return window['go']['main']['App']['StopProxy'](arg1);
}

export function UIDiag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UIDiag'](arg1, arg2, arg3);
}

export function UILog(arg1) {
  return window['go']['main']['App']['UILog'](arg1);
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
