// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfig(arg1:string):Promise<string>;

export function AddResource(arg1:string,arg2:string):Promise<string>;

export function Connect(arg1:string,arg2:string):Promise<string>;

export function DeleteConfig(arg1:string):Promise<string>;

export function DeleteResource(arg1:string):Promise<string>;

export function Disconnect():Promise<void>;

export function ListConfigs():Promise<string>;

export function ListResources():Promise<string>;

export function Ping(arg1:string):Promise<string>;

export function ReadLog():Promise<string>;

export function SetConfigGeo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Status():Promise<string>;

export function UpdateConfig(arg1:string,arg2:string):Promise<string>;
