// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string):Promise<string>;

export function Disconnect():Promise<void>;

export function LoadConfig():Promise<string>;

export function ReadLog():Promise<string>;

export function SaveConfig(arg1:string):Promise<string>;

export function Status():Promise<string>;
