// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfig(arg1) {
  return window['go']['main']['App']['AddConfig'](arg1);
}

export function AddExcludedApp(arg1, arg2) {
  return window['go']['main']['App']['AddExcludedApp'](arg1, arg2);
}

export function AddResource(arg1, arg2) {
  return window['go']['main']['App']['AddResource'](arg1, arg2);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteExcludedApp(arg1) {
  return window['go']['main']['App']['DeleteExcludedApp'](arg1);
}

export function DeleteResource(arg1) {
  return window['go']['main']['App']['DeleteResource'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ListExcludedApps() {
  return window['go']['main']['App']['ListExcludedApps']();
}

export function ListResources() {
  return window['go']['main']['App']['ListResources']();
}

export function PickExcludedAppExe() {
  return window['go']['main']['App']['PickExcludedAppExe']();
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function ProxyStatus(arg1) {
  return window['go']['main']['App']['ProxyStatus'](arg1);
}

export function ReadLog() {
  return window['go']['main']['App']['ReadLog']();
}

export function SetConfigGeo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetConfigGeo'](arg1, arg2, arg3, arg4);
}

export function StartProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopProxy(arg1) {
  return window['go']['main']['App']['StopProxy'](arg1);
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2);
}
